### ISSUE TITLE
How can I specify the rust toolchain?

### ISSUE THREAD

**Issue by nathan-at-least** [taiki-e/cache-cargo-install-action#1]
I have hit [this nightly-specific error while installing `mdbook`](https://github.com/rust-lang/rust/issues/99591), so the simplest work-around I would like to try is installing `mdbook` with cargo stable.

I didn't see any input option for selecting a toolchain. I tried setting the ambient default in a step prior to using this action, ala:

```
steps:                                                                                                                         
  - name: Select rust stable                                                                                                                                                   
    run: rustup default stable                                                                                                                                                 
  - uses: taiki-e/cache-cargo-install-action@v1                                                                                                                                
    with:                                                                                                                                                                      
      tool: mdbook@0.4.19
```

-however I run into the same error.

Questions:

- Is there a way to verify which toolchain is used in the action?
- Is there a way to specify the `stable` toolchain?
